### ISSUE TITLE
The "About" section on the landing page could be customized

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#11]
The main page has an about section. It currently has the default Wazimap information. We could expand on that to include more information.

Here are examples from other Wazimap implementations:
[Kenya](https://kenya.wazimap.org/)
[South Africa](https://wazimap.co.za/) -- uses the default about section

**Comment by ravinepal** [comment]
Thanks, @cliftonmcintosh - i'll work on the about section and get everyone's feedback!

**Comment by ravinepal** [comment]
@studenton here's the text for the homepage/about section (shared the doc with your c4n email): https://docs.google.com/document/d/1PYBGVX-hl2ZH6W3QKaO5JEMSDvX0N3lYsiIbbcD6dag/edit#

Pls note there's a text (just below the map to replace and then about section for the homepage. happy to chat via skype or FB if you have qs!
