### ISSUE TITLE
What should we do about areas (like national parks) that have no census data?

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#113]
There are some locations in our geo files that have no census data. 
[Here](https://github.com/Code4Nepal/nepalmap_app/files/594679/geo-areas-missing-census-data.xlsx) is a spreadsheet of them. Most of them are parks and wildlife reserves.

When someone selects one of these areas, an error occurs because there is no data to retrieve.

I propose we add data showing a zero for each statistic for these areas. For example, Chitwan National Park would have a population of zero. 

We could do something slightly more sophisticated and display a special page when this happens, but I'm not sure how that would behave in the other views, like maps and charts for specific tables.

**Comment by ravinepal** [comment]
@cliftonmcintosh -- zero sounds fine. perhaps more accurate would be "not available"?

**Comment by cliftonmcintosh** [comment]
The statistics I was wondering about marking as zero are numbers and I don't believe those columns will handle anything else.

**Comment by ravinepal** [comment]
zero sounds good.
