### ISSUE TITLE
Decide a LICENSE for the project

### ISSUE THREAD

**Issue by studenton** [Code4Nepal/nepalmap_app#12]

**Comment by cliftonmcintosh** [comment]
Wazimap is licensed under the MIT License. Does that affect what license can be chosen for this project?

**Comment by studenton** [comment]
Not necessarily.
http://programmers.stackexchange.com/questions/264700/paid-software-includes-mit-licensed-library-does-that-put-my-app-under-mit-too

**Comment by ravinepal** [comment]
My belief is that all of the work we do should be open for everyone's use, generally under creative commons? Perhaps something like this? 
"This work is licensed under a Creative Commons Attribution -ShareAlike 3.0 License." 

What do you guys think?

**Comment by ravinepal** [comment]
MIT License!

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Here is a pull request adding the license to the README: https://github.com/Code4Nepal/nepalmap_app/pull/63
