### ISSUE TITLE
Is there any reason not to merge the current code into the master branch?

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#121]
We've been operating exclusively on the dev branch. I propose we merge the current dev branch into master and that we update nepalmap.org so that it is built from the master branch.

If we want to verify changes before pushing to nepalmap.org, we can do so by committing to the dev branch and update the test server at http://nmtest.southcentralus.cloudapp.azure.com/. Once we are satisfied with a change, then we can merge it into master and update nepalmap.org

Suggestions and concerns appreciated, @studenton @prashishh and @ravinepal

**Comment by ravinepal** [comment]
fine with me :)

**Comment by studenton** [comment]
Sounds good.

**Comment by prashishh** [comment]
+1
