### ISSUE TITLE
Add data for population by citizenship

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#143]
Open Nepal has created a CSV based on the census data for [population by citizenship](http://data.opennepal.net/content/population-citizenship-and-sex-2011-12). Use this CSV to display that demographic information by district in NepalMap.

**Comment by crispg72** [comment]
Hi @cliftonmcintosh I'd love to help out with this, do you have any guidelines on ui? Is there another pull request that made a similar change I could use as reference?

**Comment by cliftonmcintosh** [comment]
@crispg72 

https://github.com/Code4Nepal/nepalmap_app/pull/31 is an example of a statistic that is similar. It is a demographic statistic by sex.

https://github.com/Code4Nepal/nepalmap_app/pull/17 is another similar PR.

Generally speaking, here are the steps we take to get the data into www.nepalmap.org
- convert data into a format (typically CSV) that can be used to populate a table
- write an SQL file that creates the table. See, for example, [the SQL files in the project](https://github.com/Code4Nepal/nepalmap_app/tree/dev/sql)
- link that table up with the Wazimap framework via [tables.py](https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/tables.py)
- decide how to display the data, like, for example, our [presentation of language](https://www.nepalmap.org/profiles/country-NP-nepal/#language) or [literacy rates by gender](https://www.nepalmap.org/profiles/country-NP-nepal/#literacy-by-sex).
- collect the data in the way we want to display it in the profiles section of the project, like [this for demographic data](https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/demographics.py)
- Update the HTML templates for rendering the data, like [this for demographic data](https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/templates/profile/sections/demographics.html).

The mappings from district name to `geo_code` can be found [here](https://github.com/Code4Nepal/maptools/blob/master/shared/geoidmappings.py). ("01" is the code for Taplejung.) The maptools project has samples of scripts that have been used to transform data.

**Comment by crispg72** [comment]
Thanks for the detailed instructions @cliftonmcintosh so the output csv should look something like [this](https://gist.github.com/crispg72/20706fd7c047d9624fa44d70792083a4) before converting to SQL to populate the table?

What do you do for the national totals when there aren't any in the source file should they just be summed from the district totals?

**Comment by cliftonmcintosh** [comment]
@crispg72 

Yes, we sum up the district totals to get a national total.

**Comment by cliftonmcintosh** [comment]
@crispg72 

Thank you very much for your work on this issue.

@ravinepal 

I should be able to update NepalMap on Sunday evening to include the new data that @crispg72 has added.

**Comment by crispg72** [comment]
You're welcome, it was a pleasure @cliftonmcintosh 

Initially I had a few issues on Ubuntu since I was trying on 17.04 but once I switched to 16.04 it was ok; I wouldn't mind submitting a PR to update your README.md if that would be useful?

I also have a bit of time to update some more data if you could point me in the right direction? I'm quite new to django and found it a useful learning exercise.

**Comment by cliftonmcintosh** [comment]
@crispg72 

An update to the readme would be useful and welcome.

We would certainly welcome more contributions. One data set that @ravinepal has prioritized is data on damages from flooding this year: https://github.com/Code4Nepal/nepalmap_app/issues/186

There is a Google Doc with the statistics referenced.

Some things to note about this data set:
- It will be the start of a new section on "Disasters" in NepalMap, so you would need to create a new section like [these](https://github.com/Code4Nepal/nepalmap_app/tree/dev/wazimap_np/templates/profile/sections)
- There is not data for every district, so this would require that you add zeros for the districts that are not represented in the data set
- National totals can be sums of the district-level totals

**Comment by cliftonmcintosh** [comment]
@crispg72 

https://www.nepalmap.org has been updated to include your work on citizenship and flood deaths. Thank you for your contributions.
