### ISSUE TITLE
Add data for households by female ownership of fixed assets

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#144]
I believe this is part of the 2011 census. If this has been converted to CSV by Open Nepal or another entity, use that converted data. If not, harvest the data from the census PDF.

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Do you know where this data might be? I believe this is one of the data sets suggested when we started working on NepalMap.

**Comment by ravinepal** [comment]
thanks, @cliftonmcintosh for brining this up. From 2011, we have "Female ownership of house & land" (Column L)  https://docs.google.com/spreadsheets/d/1RSip3Sl-H_UaoQDAL8P7J0XNd-RnOF9z6XC6zaQ1BCo/edit#gid=0 

There are other datasets in the doc too that might be useful.

**Comment by ravinepal** [comment]
I suppose I will close this. We can look for new data.
