### ISSUE TITLE
Add data for population by religion

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#148]
Census data detailing religion per district is in Table 8 [here](https://github.com/opennepal/datasources/blob/Population/Census/Volume05Part01.pdf), starting on page 278. Use these data to show the population by religion in each district.

**Comment by FerranMarin** [comment]
I will work on this tonight (CET) but I'd like to know what do you exactly want to be part of this issue? The SQL script to upload it into the DB or something more?

**Comment by cliftonmcintosh** [comment]
@FerranMarin 

There are several steps to adding a data set. We would welcome a contribution that accomplishes any or all of that work. First steps would be:

- extracting data from a PDF into a CSV
- converting data into a format (typically CSV) that can be used to populate a table
It is possible to do these steps as one.

The format for the data would look something like:

```
geo_code, geo_level, religion, sex, total
01,district,Hindu,male,21957
01,district,Hindu,female,23801
01,district,Buddhist,male,12308
01,district,Buddhist,female,13846
01,district,Islam,male,1
01,district,Islam,female,1
01,district,Kirati,male,24064
01,district,Kirati,female,27764
...
```
The mappings from district name to `geo_code` can be found [here](https://github.com/Code4Nepal/maptools/blob/master/shared/geoidmappings.py). ("01" is the code for Taplejung.) The maptools project also has samples of scripts that have been used to transform data.

Please note that we also need to sum up all the district entries by sex to get national totals for each religion by sex.

Because the religion data is in a PDF, converting it to a CSV in the right format will likely take some effort. If you can accomplish that, we would welcome a pull request that simply includes the data in csv format.

We would of course welcome your taking further steps as well. Beyond data conversion here are the steps we take to get the data into www.nepalmap.org

- write an SQL file that creates the table. See, for example, [the SQL files in the project](https://github.com/Code4Nepal/nepalmap_app/tree/dev/sql)
- link that table up with the Wazimap framework via tables.py
- decide how to display the data, like, for example, our [presentation of language](https://www.nepalmap.org/profiles/country-NP-nepal/#language) or [literacy rates by gender](https://www.nepalmap.org/profiles/country-NP-nepal/#literacy-by-sex).
- collect the data in the way we want to display it in the profiles section of the project, like [this for demographic data](https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/demographics.py)
- Update the HTML templates for rendering the data, like [this for demographic data](https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/templates/profile/sections/demographics.html).

**Comment by FerranMarin** [comment]
Awesome! Thanks for the detailed guide.

Sorry for the radio silence, been away on holidays and was hard to go online. I'll start working on this :)

**Comment by FerranMarin** [comment]
Hello @cliftonmcintosh ,

Sorry for the slow pace, I finally have a csv and an sql file ready to upload. But I can only find where to place the SQL file, where should I upload the csv to?

**Comment by cliftonmcintosh** [comment]
if the SQL file has the data, that is sufficient. If you would like to submit the CSV, we have a data project. We also have a "maptools" project if you would like to submit a PR that contains the script you used to create the CSV.

**Comment by FerranMarin** [comment]
Do you have a link to the data project so I upload the csv? I'll be uploading the sql in a moment :)

**Comment by cliftonmcintosh** [comment]
https://github.com/Code4Nepal/data

**Comment by cliftonmcintosh** [comment]
@FerranMarin 

I believe there is a duplicate row in the data right now. When I ran the sql file, I got this error:

```
ERROR:  could not create unique index "religion_pkey"
DETAIL:  Key (geo_level, geo_code, religion, sex)=(district, 41, Hindu, Male) is duplicated.
```

As you work on adding the data to NepalMap, that will need to be corrected.

**Comment by FerranMarin** [comment]
Will double check and correct it. Gimme a few minutes :)

**Comment by cliftonmcintosh** [comment]
@FerranMarin 

I did a quick check by taking just the district code column and doing 

```
sort religiondistricts.csv | uniq --count --repeated | grep -v 22
```

It looks like there are three districts that may be off.

District 07
District 27
District 41

There are also some missing districts.
District 20
District 24
District 38

I'm not sure if this is a problem with the original data set or with the transformation

**Comment by FerranMarin** [comment]
I will be checking the rest of the districts, for the previous case it was the transformation. Expect this to be done in around half hour or so.

**Comment by cliftonmcintosh** [comment]
@FerranMarin,

Are you interested in and able to take the next steps to integrate the data into NepalMap? Your contribution would be welcome. If you do not have the time to do the next steps, I will invite others to contribute.

**Comment by FerranMarin** [comment]
I'd love to, but I believe my workload at my actual work will increase in the next few weeks, if someone else is interested in catching up from where I left, that's ok with me.  :)

**Comment by cliftonmcintosh** [comment]
Thanks for what you've done so far. I'll see if I or someone else can complete the integration of the data soon
