### ISSUE TITLE
Add data for health facilities

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#149]
Can this data set be adapted to list the number and type of health facilities in each municipality/village?

https://data.humdata.org/dataset/nepal-health-facilities-cod

**Comment by cliftonmcintosh** [comment]
@Bezzy1999 

Thank you for your interest in contributing. We would love to have this data available. At the same time, it is a data set that could be complicated to collected. For collecting these data into a CSV, here are some guidelines:
Figure out what all the different types of health facilities are. Looking over the map, I see things like "Health Post", "Sub Health Post", "Hospital", "District Cold Room", and "Ayurvedic Aushadhalaya". I am sure there are other types.
For each district in Nepal, list the total number of each type of health facility that is present. If one of the types is not present in that district, list "0" for the number of that type in the district.
The data would looks something like this:
district, facility type, total
Dadeldhura, Sub Health Post, 10
Dadeldhura, Hospital, 1
Dadeldhura, Ayurvedic Aushadhalaya, 2
Dadeldhura, Teaching Hospital, 0

Those are not real statistics. They are just examples of the sort of thing we would want as a first step. Once that is done, then integrating the data into NepalMap would be the next step.

Here is some general information about collecting and visualizing data in NepalMap: https://github.com/Code4Nepal/nepalmap_app/wiki/Collecting-and-visualizing-data-in-NepalMap

If you can only get to the first step of extracting data from the map, we would ask that the contribution be stored in our data project instead of in NepalMap. From there another contributor can transform it into data usable in NepalMap.

**Comment by Bezzy1999** [comment]
Hi @cliftonmcintosh I have got the data into a format for importing into nepalmap and plan on doing that tomorrow.

I added this in a pr for you to check whether I have combined the health facilities into the required groups and also to check whether some of the unknown data from the GIS files are important, the output of that code currently looks like this:

```
[0, '', 'Dailekh', 'Belpata', 'M-BHE-60-008'] not in facility_type_map
Unknown district: [0, '', '', '', '']
[0, '', 'Sarlahi', 'Manpur', 'C-JAN-19-065'] not in facility_type_map
[0, '', 'Sarlahi', 'Manpur', 'C-JAN-19-065'] not in facility_type_map
[0, '', 'Sarlahi', 'Manpur', 'C-JAN-19-065'] not in facility_type_map
[0, '', 'Mahottari', 'Bijayalpura', 'C-JAN-18-015'] not in facility_type_map
[0, '', 'Sarlahi', 'ChandraNagar', 'C-JAN-19-021'] not in facility_type_map
[0, '', 'Mahottari', 'Hatisarwa', 'C-JAN-18-033'] not in facility_type_map
[0, '', 'Mahottari', 'Singyahi', 'C-JAN-18-070'] not in facility_type_map
Unknown district: [0, 'Central Hospital', '', '', '']
Unknown district: [0, 'Central Hospital', '', '', '']
Unknown district: [0, 'Central Hospital', '', '', '']
Unknown district: [0, 'Central Hospital', '', '', '']
Unknown district: [0, 'Central Hospital', '', '', '']
Unknown district: [0, 'Central Hospital', '', '', '']
Unknown district: [0, 'Zonal Hospital', '', '', '']
```

Let me know your thoughts...

**Comment by cliftonmcintosh** [comment]
@Bezzy1999 

Thanks for all the work on this. I think having this data will be valuable.

I'm not sure how to deal with those facilities that don't match up correctly. My first thought is that given the large volume of data, some mismatched facilities will be fine. If these facilities cannot be matched to a district, then I think proceeding without them is acceptable.

For "Central Hospital" we may be able to look at the overall totals and figure out where they belong. For example, if there are 75 Central Hospitals and only 69 districts where the Central Hospital was added correctly, then it may be safe to assume that every district has a Central Hospital and then we can simply add one to the 6 districts that are missing them. Then again, I don't know what a Central Hospital is or whether there should be one per district or not.

If there is only one Zonal Hospital that is unassigned, that may be easy for us to figure out. There were 14 zones in Nepal at the time this data was collected. We may be able to ask someone where all the zonal hospitals should be located and then fix that one that was not correctly assigned in the data.

For now, though, I would suggest proceeding and leaving the mismatched facilities out. I think we will have the opportunity to update the data if/when we can accurately determine where the mismatched facilities should go.
