### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by prashishh** [Code4Nepal/nepalmap_app#16]
Setup development environment for the project.

- [ ] AWS
- [ ] Heroku
- [ ] Google app engine

**Comment by ravinepal** [comment]
sounds like  EC2 from Amazon, is a good option. We will will have to pay if we get huge traffic. so for us, AWS, works well. I can create Code for Nepal's account, and share the details. 

I found this useful as I consdiered options: https://www.quora.com/Is-there-somewhere-I-can-host-my-django-web-app-for-free

**Comment by prashishh** [comment]
EC2 it is!

**Comment by prashishh** [comment]
I did a bit of research and it is clear which one is more cost effective for our long term use. We could use either Heroku or AWS for our development, but for production, we will need to weigh in both Heroku & Django. 

I think dev environment will be a good testing ground for both cloud platforms.

**Comment by prashishh** [comment]
Reference for AWS Elasticbeanstalk: http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-django.html

**Comment by prashishh** [comment]
Update: @prerakpradhan is going to help us deploy the application to AWS Elastic Beanstalk. I have sent the credentials to him for further progress.

He is currently working with Microsoft Azure team but has good experience with AWS.

**Comment by prashishh** [comment]
Thanks to @prerakpradhan, we were able to host our dev instance in Azure - http://13.93.215.195:8000/

**Comment by ravinepal** [comment]
This is great, prashish! Thank you so much @prerakpradhan! pls email me details at ravi@codefornepal.org to direct http://13.93.215.195:8000/ to our godaddy domain!
