### ISSUE TITLE
Incorrect adherence to licence terms

### ISSUE THREAD

**Issue by adieyal** [Code4Nepal/nepalmap_app#170]
I just had a look at the licence of your codebase and it seems that you have changed the original upstream licence.  This is probably accidental but please review the terms of the licence here:
https://github.com/Code4SA/wazimap/blob/master/LICENSE.

**Comment by cliftonmcintosh** [comment]
@adieyal 

Thank you for bringing this to our attention. I believe we had added the base MIT license with the understanding that it was the same. Can you please provide some guidance with regards to the license. Do we need to include the license exactly from https://github.com/Code4SA/wazimap/blob/master/LICENSE? Is the key line we are missing `Copyright (c) 2014 Census Reporter` ?

**Comment by cliftonmcintosh** [comment]
@adieyal 

We are happy to make updates. If you can provide guidance, we would appreciate it. Absent any guidance, it is my understanding that the following changes will meet the request: 
1. Replace the license text with the license at https://github.com/Code4SA/wazimap/blob/master/LICENSE 
2. Update the about section on [NepalMap](https://www.nepalmap.org/) to include the following:
"NepalMap is based on [Wazimap](https://github.com/Code4SA/wazimap) which is a fork of [Census Reporter](https://censusreporter.org/). Wazimap is a joint project of [Media Monitoring Africa](http://www.mediamonitoringafrica.org/) and [Code for South Africa](http://code4sa.org/)."

**Comment by adieyal** [comment]
My apologies - i was mistaken with regards to how wazimap was being used. I thought that you had cloned the project rather than used it as a library. As it stands, I think your current licence is perfect.
