### ISSUE TITLE
Keeping branches in sync before environments are set up

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#18]
Can we keep the master, test and dev branches in sync until environments are spun up?

Here is my suggestion:

- All pull requests are made on the dev branch. 
- As long as there is no test environment and no production environment, whenever a pull request is merged in dev, we also merge it into test and master.
- When we have a test environment spun up, we stop automatically merging dev into test and master.
-  However, until a production environment is spun up, every time we merge into test, we also merge the same commits into master.
- After a production environment is spun up, we start treating all three branches separately, merging into test only what we want in the test environment and merging into master only what we want into production

**Comment by studenton** [comment]
@prashishh

**Comment by prashishh** [comment]
@cliftonmcintosh - What is the reason for suggesting this flow? Until the production or test environment is up, there isn't any reason to merge `dev` to `test` or `master`. I'm not against it though. If you think it should be the case, let's merge `dev` to `test` and `master`. +1

**Comment by cliftonmcintosh** [comment]
@prashishh 

It's true. `master` and `test` are totally unused right now, so merging the `dev` branch into them will have no effect. On the other hand, the complexity of separate branches is only there to "protect" the `master` branch and the `test` branch. Until that code is being used, we have nothing to protect. 

I don't have strong feelings about this.

What I propose as an alternative is to set the `dev` branch as the default in GitHub so that when we go to the project in GitHub, we can what we are actively working on without having to switch to the `dev` branch manually.

**Comment by prashishh** [comment]
I agree @cliftonmcintosh. 👍

**Comment by cliftonmcintosh** [comment]
I've set the default branch to `dev`.
