### ISSUE TITLE
data on chitwan

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#180]
Cliff - a user flagged this to me. can we check to see if the data is not being presented correctly: https://twitter.com/anilbhattarai/status/889179664287191041

**Comment by cliftonmcintosh** [comment]
@ravinepal 

120% is the official statistic for Chitwan. Please see page 375 [of the report](http://dohs.gov.np/annual-report/annual-report-fy-207172/). I mentioned in [my pull request](https://github.com/Code4Nepal/nepalmap_app/pull/174) for those data that there were potential problems.

In our email exchange of June 1-2 (see the subject "pull request for data on maternal deaths in childbirth"), it was decided that we would publish it. I believe you suggested it might be good to have a blog post in which we discuss potential reliability problems.

**Comment by ravinepal** [comment]
Thanks, @cliftonmcintosh. Yes, I'll respond to the Twitter user.
