### ISSUE TITLE
Forest and Watershed profile of Local Level(744) Structure

### ISSUE THREAD

**Issue by amitness** [Code4Nepal/nepalmap_app#181]
Found this on social media. Could be useful data for adding to NepalMap. 

https://drive.google.com/drive/folders/1IpU27W8bWrrcpjkyK-2SnV7TXw

**Comment by amitness** [comment]
@ravinepal Have a look. If it is useful, I'll work on it to convert it into CSV.

**Comment by ravinepal** [comment]
Thanks, @amitness! Pls go ahead. Do you know the original data source? 

Also cc'ing @cliftonmcintosh for his info.

**Comment by cliftonmcintosh** [comment]
@amitness,

Here are the conditions for the data to work in the Wazimap platform:

- There is data for every unit at the district or VPC level.
- There is a numeric value that can be used for each unit at whatever level we are reporting on.

For these data, it looks like what would work well would be to have the total area of a district in square kilometres as well as the forested area of a district in square kilometres. This would allow us to report on the percentage of each district that is forested.

**Comment by amitness** [comment]
@ravinepal I found it from here: https://www.facebook.com/rajkumarrimal/posts/10209663700813988 . He seems to be associated with the forestry department.

**Comment by amitness** [comment]
I have extracted the dataset as what @cliftonmcintosh said. But there is a problem:

1. Nawalparasi has been repeated in two states Pradesh 4 as well as Pradesh 5.
2. Rukum has been repeated in two states Pradesh 5 and 6.

So we've a data like:
Rukum | 652.1 | 1212.7
Rukum | 556.5 | 1160.7

I did some research and seems the district is part of two states. For Rukum, it's divided into eastern part and western part. Eastern is in state 5 and western is in state 6.

I think we can sum the two repeated values and we'll get a single district's area. @ravinepal What do you think?

**Comment by amitness** [comment]
I pushed the dataset here: https://github.com/Code4Nepal/data/tree/master/datasets/forestry
The area given is in sq. km.

@cliftonmcintosh

**Comment by ravinepal** [comment]
thanks, @amitness! The primary source seems to be: Ministry of Forest and Soil Conservation, based on this document: https://drive.google.com/drive/folders/1IpU27W8bWrrcpjkyK-2SnV7TXw 

I wonder if Rukum and NawalParasi are located in two states? In that case - we combine the data?

**Comment by amitness** [comment]
@ravinepal Yes, I combined it.

**Comment by cliftonmcintosh** [comment]
@amitness 

I think https://github.com/Code4Nepal/data/tree/master/datasets/forestry has 74 districts. Is there one for which we don't have data?

**Comment by amitness** [comment]
@cliftonmcintosh Fixed it. Now all 75 districts data is there.

**Comment by cliftonmcintosh** [comment]
@amitness 

Thanks. I've tagged this as being in the data pipeline and moved it into the backlog on ZenHub.

I am currently working on a business data set. If we don't have other volunteers to work on integrating this data set, I can do it next.

**Comment by cliftonmcintosh** [comment]
@amitness 

Is the unit of measurement in the CSV square kilometres?

**Comment by cliftonmcintosh** [comment]
@amitness and @ravinepal 

Do we have a direct link to the document on the Department of Soil Conservation and Water Management's website or on an official government repository? If not, can we load the original PDF of the [report](https://drive.google.com/drive/folders/1IpU27W8bWrrcpjkyK-2SnV7TXw) into our data section on GitHub?

**Comment by amitness** [comment]
@cliftonmcintosh Actually, I got this data from a [facebook post](https://www.facebook.com/rajkumarrimal/posts/10209663700813988) by Raj Kumar Rimal, who is a Forest Officer at Department of forest. In the post, he tells
>नेपालको प्रदेश तथा स्थानिय तह अनुसार (गाँउ, नगर, उप महानगर तथा महानगर) वन क्षेत्र तथा गैह्र वन क्षेत्रका नक्साहरू डाउनलोड गराै । धेरै भन्दा धेरै सेयर गराै । हरेक वनकर्मी, स्थानियतहका जन प्रतिनिधीहरूको लागि उपयुक्त एटलस सावित हुनेछ । सवै संलग्न प्राविधिक साथीहरू बधाइको पात्र हुनुहुन्छ ।

The literal translation being:
"These are the maps of Nepal federal states and local VDCs and inner areas. Please share it as much as possible. It's suitable as a atlas for every forest officer and public representatives."

They're themselves using Google Drive for hosting the maps and reports.

**Comment by cliftonmcintosh** [comment]
Amit,

Thanks for the context and the information. I will update the Sources link
to include that Google Drive location.

Cliff
