### ISSUE TITLE
Update colors to match C4N design scheme

### ISSUE THREAD

**Issue by amitness** [Code4Nepal/nepalmap_app#182]
Some sections where stylesheet colors are still  Wazimap defaults:
- [ ] http://nepalmap.org/data/table/?table=CHILD_NOURISHMENT&geo_ids=district-27&primary_geo_id=district-27
- [ ] **Show data** table
- [ ] Embed popup

**Comment by ravinepal** [comment]
@amitness - am closing this for now. pls feel free to reopen if you would like...
