### ISSUE TITLE
Add earthquake data

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#185]
Update NepalMap to include data on deaths and houses destroyed by district in the earthquake

https://codefornepal.carto.com/tables/merge_of_earthquake_deaths_2c_houses_destroyed/public

**Comment by cliftonmcintosh** [comment]
@ravinepal 

In https://github.com/Code4Nepal/nepalmap_app/issues/187, you mentioned a [different data set](https://docs.google.com/spreadsheets/d/1WGEsVT0eiWnE34uA9-z3a4cKStcYhCvo_3ANiVzZTYk/edit?ts=59c8020a#gid=617759520) for earthquakes and floods. That data set seems different from what is mentioned above.

As I understand it, the [carto data set above](https://codefornepal.carto.com/tables/merge_of_earthquake_deaths_2c_houses_destroyed/public) has data on earthquake-related:
- deaths
- injuries
- houses destroyed
- houses damaged

I assume that is what we should focus on for earthquake data. Is that correct?

**Comment by cliftonmcintosh** [comment]
@suvash has volunteered to work on this data set

**Comment by ravinepal** [comment]
Sorry @cliftonmcintosh for providing two datasets. Yes, pls use carto data set above for the earthquake.

**Comment by cliftonmcintosh** [comment]
@suvash 

Please note that @crispg72 has added a "Disasters" section to NepalMap. Your work on earthquake data should be placed in that section.

**Comment by suvash** [comment]
Hi again. I'm barely being able to make time to work on this :( I'll give it a go again sometime soon. If I'm not able to come back in a month, feel free to reassign @cliftonmcintosh

**Comment by ravinepal** [comment]
I believe this has been resolved.
