### ISSUE TITLE
Add data on foreign aid in Nepal

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#187]

**Comment by suvash** [comment]
Possible source: https://github.com/opennepal/odp-foreign-aid

**Comment by ravinepal** [comment]
Guys I have downloaded the latest data. I need to normalize, clean and
share with you. Sorry for the delay. Will do in a few days

**Comment by ravinepal** [comment]
Hi @suvash here's the data: https://docs.google.com/spreadsheets/d/17Bu7OxGEj2ewcoQFpu50VSNPtEojbHgb_MiNuAHitAA/edit?usp=sharing 

Here's the source: http://mof.gov.np/ieccd/newsbook/20160424154147.pdf   (Annex 3)

**Comment by cliftonmcintosh** [comment]
@ravinepal and @suvash 

Sheet 2 of that spreadsheet should be easy to display, with "Total number of projects" and "Total actual disbursement" as separate data points. If Suvash is going to work on the earthquake statistics, I can take this one on.

Ravi, the first sheet in that document has headers but no data. Was that intentional?

**Comment by ravinepal** [comment]
thanks, @cliftonmcintosh. Yeah Sheet 2 is the useful one. I deleted sheet 1.

**Comment by suvash** [comment]
Haven't quite gotten to it. Hopefully, I'll have some more time this week to poke around the earthquake dataset.

**Comment by cliftonmcintosh** [comment]
I will do the foreign aid data too allow you to work on the earthquake data

**Comment by ravinepal** [comment]
@suvash - here's the flood and earthquake data (clean sheet tab): https://docs.google.com/spreadsheets/d/1WGEsVT0eiWnE34uA9-z3a4cKStcYhCvo_3ANiVzZTYk/edit?ts=59c8020a#gid=617759520

**Comment by cliftonmcintosh** [comment]
To keep the issues clear, it might be useful for us to discuss the flood and earthquake data using these GitHub issues:

- earthquake: https://github.com/Code4Nepal/nepalmap_app/issues/185
- flood: https://github.com/Code4Nepal/nepalmap_app/issues/186

**Comment by cliftonmcintosh** [comment]
@ravinepal 

How do we do national totals for the number of projects? Are some projects ongoing in more than one district? Is each project that is listed limited to a single district?

I don't want to overcount. For example, if there is a World Bank project that is active in both Lamjung and Gorkha, we don't want to have that count as 2 projects in the national total.

Do you have guidance on how we should display national totals?

**Comment by ravinepal** [comment]
thanks, @cliftonmcintosh. the data I shared doesn't include nationwide projects as the GoN only included district level projects in Annex 3 of this document: http://mof.gov.np/ieccd/newsbook/20160424154147.pdf (If it's ok, I'll suggest displaying district level disbursement and number projects.) 

I will still need to find total number of national projects. But "**the volume of foreign aid disbursement in FY 2014-15 reached a total of US$ 1.13 billion** of which Official Development Assistance contribution was US$ 1020.75 million (90%) and INGO contribution was US$ 116.89 million (10%) in this period.([page 28](http://mof.gov.np/ieccd/newsbook/20160424154147.pdf))

Does this help?

**Comment by cliftonmcintosh** [comment]
@ravinepal 

I will work on the district-level totals. I do not know yet if there will be issues with not having totals for the country. I don't know how the Wazimap framework will behave. We have situations where we have national totals but not district totals and situations where we have district totals but not VDC totals. Those work okay. However, we have never tried a data set where a smaller unit (like a district) has data but the larger unit (like a country) does not.

**Comment by cliftonmcintosh** [comment]
@ravinepal 

I have tried to import the development assistance data. However, it appears that Wazimap requires that we have data at the country level as well. I believe that is because the Wazimap framework always tries to provide a comparison between the current level and the national level. See, for example, the "about the same as the figure in Nepal" and the "a little less than the amount in Nepal" entries in this view of life expectancy and income.

I will explore if there is a possibility of turning this off for a specific statistic, but I do not know yet if that is possible. If that is not possible, what are the chances that we could get country-wide data for the number of development assistance projects and the amount of development assistance?

![auto-comparison-to-country-level](https://user-images.githubusercontent.com/3824492/31586997-1d8f4920-b19f-11e7-9b54-3074f00cd294.png)

**Comment by ravinepal** [comment]
Hi @cliftonmcintosh - sorry i missed this earlier. 

Let's calculate what we have for districts & clarify with this text: 
Aid disbursement by district for fiscal Year 2014 -15 (Nationwide projects excluded) 
Source: [mof.gov.np (PDF)](http://mof.gov.np/ieccd/newsbook/20160424154147.pdf)
