### ISSUE TITLE
Prioritize upcoming data sets

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#188]
@ravinepal 

We have several potential data sets that we can include. Can you take a minute and prioritize them?

Here are the data-set issues that I believe need prioritizing:

#181 -- forest and watershed
#185 -- earthquake
#186 -- flood
#187 --  foreign aid

We also have older issues that haven't been addressed. If some of those have data and are more important, having them go first would be good.

**Comment by ravinepal** [comment]
sorry @cliftonmcintosh I missed this earlier. Thanks for the reminder. I'd say pls go ahead with these: 

#181 -- forest and watershed
#185 -- earthquake

I'll soon clean data fro flood and foreign aid and share.

**Comment by ravinepal** [comment]
#187 -- foreign aid
#186 -- flood
#185 -- earthquake

**Comment by ravinepal** [comment]
closing this for now. We can create a new issue when we are ready.
