### ISSUE TITLE
Scrape data about agricultural production in Nepal

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#203]
Here's the dataset published by the Government of Nepal: http://moad.gov.np/public/uploads/1142453195-STATISTIC%20AGRICULTURE%20BOOK_2016.pdf 

We'd like to scrape and visualize from the document: 
Major Cereal Crops by Districts 
Cash Crops by Districts 
Oil Seed Crops by Districts
 Jute by Districts
 Cotton by Districts 
 Tea by Districts
 Coffee by Districts
Pulses by Districts
Live Stock Population by Districts
Milk Animals and Milk Production by Districts
Net Meat Production by Districts
Egg Production by Districts
Wool Production by Districts
Yak/ Nak/ Chauri Population by Districts
Rabbit Population by Districts
 Horse/Asses Population by Districts 
 Water Surface Area and production of fish by Districts 
 Citrus Fruits: Area, Productive Area, Production, and Yield by Districts
Summer Fruits: Area, Productive Area, Production, and Yield by Districts
Fresh Vegetable Crops: Districtwise Area, Production and Yield

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Would it make sense to collect data in the [C4N data project](https://github.com/Code4Nepal/data)? This would allow people to contribute to data collection without having to take all the steps necessary to make it readable and usable by NepalMap.

For example, @robalaban has contributed a CSV of coffee production. His data set will be useful for NepalMap, but it will still require other steps before it can be published on NepalMap.

I am not sure that NepalMap is the most useful place for data sets. Having contributors submit pull requests against the data project instead would give us a place to collect the data and tools that created the data. It makes them visible on their own, too.

**Comment by ravinepal** [comment]
Thanks, @cliftonmcintosh. That's a good idea. Let's do that. I will create this list on C4N data project.

**Comment by ravinepal** [comment]
This issue has been migrated to our [data project](https://github.com/Code4Nepal/data/issues/2). Thank you in advance for helping us.
