### ISSUE TITLE
VDC level metadata

### ISSUE THREAD

**Issue by amitness** [Code4Nepal/nepalmap_app#209]
http://lgcdp.gov.np/nepal-new-structure-gaupalika-nagarpalika-list

**Comment by amitness** [comment]
Someone is scraping this data into CSV and will be opensourcing it soon here: https://github.com/code-geek/old_vdc_to_new_gaupalika_mapping_table

**Comment by cliftonmcintosh** [comment]
@amitness
 Is this data for the new local governments? What kind of metadata is it?

**Comment by amitness** [comment]
- Municipality Name
-- Population
-- Area
-- Borders on east, west, north, south
-- Number of wards
-- Wards in the municipality and their symbol no.

**Comment by amitness** [comment]
Yes, it's for the new local government.

**Comment by cliftonmcintosh** [comment]
@amitness 

I believe presenting this data will require a separate instance of NepalMap that is built on the new local geographical boundaries. That is because our framework is not designed to present two competing sets of geographical boundaries.
