### ISSUE TITLE
Show population above SLC (National examination of grade 10 passed) by major field of study

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#21]
This is part of number 2 in the data pipeline

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Can you provide a comment to this ticket with a link to the data for population above SLC by major field of study?

**Comment by ravinepal** [comment]
@cliftonmcintosh thanks. we'd like to. pls allow me to find data and get back to you soon.
