### ISSUE TITLE
Customization of the platform to meet Code for Nepal color guidelines

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#30]
hi team, we use three colors at code for nepal: 

Red: #E00015
Blue: #00ADEF 
White: #ffffff

for example, check out www.asknepal.info

**Comment by studenton** [comment]
I'll look into this.

**Comment by ravinepal** [comment]
@studenton thanks for making some changes! Could you pls also make the background white? and then pls push the update to reflect on http://13.93.215.195:8000/

**Comment by studenton** [comment]
@ravinepal I'll need the server details for http://13.93.215.195:8000 to push the changes.

**Comment by codefornepal** [comment]
thanks, @studenton/ @prashishh and @prerakpradhan -- grateful if you could email server details at amit@codefornepal.org and ravi@codefornepal.org We will share with Cliff as well.  Thanks! (We should make some of these changes soon to avoid any copyright issue. Amit is kindly making it a priority.)
