### ISSUE TITLE
age range for education level

### ISSUE THREAD

**Issue by cliftonmcintosh** [Code4Nepal/nepalmap_app#35]
@studenton and @ravinepal 
Can you confirm the age range for education level? I ask because the totals are different for POPULATION_EDUCATION_LEVEL_PASSED.csv and POPULATION_LITERACY_STATUS_AND_SEX_5_AND_ABOVE.csv. If my script is correct, there are 16,101,177 people in education level but 23,926,541. If you can let me know what the age range is for education level, I can adjust the text in Nepal Map.

**Comment by ravinepal** [comment]
@cliftonmcintosh sorry for the confusion. This data is the most accurate -- the age range is 5 and above: https://github.com/codefornepal/data/blob/master/datasets/census/population_education_level.csv

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Thanks. That's interesting that the census would use age 5 and up is the population for education level passed. It seems to me like adults would be a more sensible age group. After all, the number of 5 year olds with an SLC will surely always be zero!

@studenton 

Will this data set be imported into census-data or do we need to import it directly into the map project?
