### ISSUE TITLE
change background color

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#50]
@studenton @cliftonmcintosh - i was thinking we have background color of the homepage to alternate between #FFF and #F7F7F7. I think that makes the site look much cleaner. What do you think? 
![screen shot 2016-10-09 at 8 03 49 am](https://cloud.githubusercontent.com/assets/3759081/19220255/15bdda12-8df7-11e6-891a-d47423d66cfc.png)

If you guys agree, @studenton - could you pls make the changes when you can! thanks!

**Comment by studenton** [comment]
@ravinepal It's a good idea. I'll work on it.

**Comment by ravinepal** [comment]
thanks, @studenton! could you pls also add code for nepal logo/URL on the top right corner after Twitter logo, like they have here: https://wazimap.co.za/ (Sorry I know you had suggested earlier and I said it's ok to not have it. Now I think it would be useful to have c4n logo on the top right corner.)

**Comment by studenton** [comment]
@ravinepal Tried it but since our we don't have logo of that dimension, it isn't looking good. I tried cropping it, but image looks distorted and unusual. If any designer can help us make logo of 467 * 75 pixels, it would fit perfectly.

**Comment by ravinepal** [comment]
thanks, @studenton! I'll ask a designer. In the meantime, can you use this logo? 
![codefornepal_logo_latest](https://cloud.githubusercontent.com/assets/3759081/19294808/ec1784ca-8ffd-11e6-86c6-4c107bebbd60.jpg)

**Comment by ravinepal** [comment]
![codefornepal_logo](https://cloud.githubusercontent.com/assets/3759081/19294864/53fadd1c-8ffe-11e6-9dd6-84c5eafc1881.jpg)
Thanks, @studenton! I'll ask a designer! In the meantime, can you use this logo?

**Comment by studenton** [comment]
@ravinepal Nope, that logo doesn't fit it either.
![screenshot from 2016-10-16 18 11 53](https://cloud.githubusercontent.com/assets/8587189/19417414/216bc79a-93cc-11e6-81f2-db1185e99ad2.png)

**Comment by ravinepal** [comment]
thanks, @studenton!
