### ISSUE TITLE
Map view of tabular data doesn't work

### ISSUE THREAD

**Issue by prashishh** [Code4Nepal/nepalmap_app#65]
Steps to reproduce:
- Search by District
<img width="1139" alt="screen shot 2016-10-17 at 10 48 32 pm" src="https://cloud.githubusercontent.com/assets/966151/19465839/e238b86c-94bb-11e6-89dd-393756b8ce2f.png">
- Select "Show data" of any visualization. (lower right of a graph)
- Select "Map" view.

<img width="519" alt="screen shot 2016-10-17 at 10 45 53 pm" src="https://cloud.githubusercontent.com/assets/966151/19465816/ad6abbc6-94bb-11e6-887c-f3f8807e0f63.png">

**Comment by cliftonmcintosh** [comment]
It [doesn't work in Wazimap Kenya](https://kenya.wazimap.org/data/map/?table=AGEINCOMPLETEDYEARS_RURALORURBAN_SEX&geo_ids=county|country-KE&primary_geo_id=county-8), either, so this may be a bug in the framework.

Wazimap Kenya has hidden the Find Data element on the main page, but the failing map view can still be accessed there via the Show Data link under a chart. From there, the map view of the chart fails. Screenshots here:
<img width="871" alt="no find data element" src="https://cloud.githubusercontent.com/assets/3824492/19478233/6076860a-9507-11e6-8231-9a4e81b6ecbc.png">

<img width="669" alt="access to data map view view Show Data under chart" src="https://cloud.githubusercontent.com/assets/3824492/19478243/69117bc6-9507-11e6-9de5-f7ce6bdc85de.png">

**Comment by cliftonmcintosh** [comment]
I have created a [PR for Wazimap](https://github.com/Code4SA/wazimap/pull/57) to correct a JavaScript error that appeared to be causing this bug.

Here's a screenshot of what it looks like locally after fixing that bug.

![data-map-sample-load](https://cloud.githubusercontent.com/assets/3824492/19584415/e2c1a938-9709-11e6-8d8b-fd04c897d804.png)

**Comment by cliftonmcintosh** [comment]
This fix has been deployed to www.nepalmap.org

![issue-65-fix-screenshot](https://cloud.githubusercontent.com/assets/3824492/19616077/0422ea1c-97d0-11e6-9dbd-de729a867172.png)
