### ISSUE TITLE
Twitter link in the navigation bar

### ISSUE THREAD

**Issue by prashishh** [Code4Nepal/nepalmap_app#67]
Twitter icon in the navigation bar takes you away from the website.

<img width="382" alt="screen shot 2016-10-17 at 11 23 35 pm" src="https://cloud.githubusercontent.com/assets/966151/19466579/be132c92-94c0-11e6-9839-2b3d6f2af84f.png">

**Comment by studenton** [comment]
I gave it a try. The wazimap base template is structured in such a way that you can't override the twitter logo section. To change it, I had to override the whole head block.

Have a look at this [commit](https://github.com/studenton/nepalmap_app/commit/257aa93ed3877a8da6310c82de65eb0e75a7e2cf)

For the time being, this is the only way. Should I merge it? @prashishh 

I have opened a [new issue](https://github.com/Code4SA/wazimap/issues/55) on the wazimap repo  regarding this.

**Comment by prashishh** [comment]
Great job! Did you verify responsiveness of the new code block?

With this customization, we can be creative to what we can add in the navigation bar instead of the twitter handle.

**Comment by studenton** [comment]
It's responsive. Yes, I'll push it to the main repo then?

**Comment by prashishh** [comment]
Please go ahead.
