### ISSUE TITLE
Write Instruction to download data in README

### ISSUE THREAD

**Issue by prashishh** [Code4Nepal/nepalmap_app#69]
One of the nicest feature of Wazimap is to allow people to download certain portions of data in different universal formats. We should write that in the About section & README to encourage people to download and play with data.

**Comment by studenton** [comment]
How about using video? Here's a screencast I made.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/hm9nQQT8OWY/0.jpg)](https://www.youtube.com/watch?v=hm9nQQT8OWY)

**Comment by AbhayGoyal** [comment]
How can i get hold of the software to write the step by step process?

**Comment by ravinepal** [comment]
Roshan created this video: https://www.facebook.com/codefornepal/videos/647380015471250/
