### ISSUE TITLE
Integrate Analytics

### ISSUE THREAD

**Issue by prashishh** [Code4Nepal/nepalmap_app#72]
Integrate Google Analytics or any other  other analytics to understand behavior. 

We can also try to understand which data set people are looking for in search (and failing)?

**Comment by studenton** [comment]
If we go with Google Analytics, we'll need to add a Privacy Policy as well.

Here's a snippet from the google TOS:

> You will not (and will not allow any third party to) use the Service to track, collect or upload any data that personally identifies an individual (such as a name, email address or billing information), or other data which can be reasonably linked to such information by Google. You will have and abide by an appropriate Privacy Policy and will comply with all applicable laws and regulations relating to the collection of information from Visitors. **You must post a Privacy Policy** and that Privacy Policy must provide notice of Your use of cookies that are used to collect traffic data, and You must not circumvent any privacy features (e.g., an opt-out) that are part of the Service.

**Comment by prashishh** [comment]
Makes sense. I'll look around if similar apps in the web have analytics in them.

**Comment by studenton** [comment]
#78
