### ISSUE TITLE
fix logo on map display page

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#82]
@studenton -- i just there are still some pages where we see the old logo. could you pls take it out when you get a chance? http://www.nepalmap.org/data/map/?table=HOMEOWNERSHIP&geo_ids=country-NP,district|country-NP&primary_geo_id=country-NP#column%7COWNED%2Csumlev%7Cdistrict

**Comment by studenton** [comment]
Fixed @ravinepal

**Comment by ravinepal** [comment]
Thanks, @studenton!
