### ISSUE TITLE
Extract and clean population projection for 2030 

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#87]
@studenton I know you had started to extract and clean the data. Could you pls upload the file on Github when you can. If we can add the projection data for 2030 -- then it'd be nice as the last census was in 2011--almost 6 years ago! it'd be good to have data that helps us realize what to expect in the future :) 

Here's PDF if you need: http://cbs.gov.np/image/data/Population/Population%20projection%202011-2031/PopulationProjection2011-2031.pdf

**Comment by cliftonmcintosh** [comment]
@studenton This is done, right?

**Comment by studenton** [comment]
@cliftonmcintosh No. Only a portion of the PDF has been been scraped.

**Comment by studenton** [comment]
Completed [all](https://github.com/Code4Nepal/population-projection).

**Comment by ravinepal** [comment]
Thanks, @studenton! This is great!!
