### ISSUE TITLE
add fb & c4n favicon by twitter on nepamap 

### ISSUE THREAD

**Issue by ravinepal** [Code4Nepal/nepalmap_app#95]
amit - just wanted to create the issue as you asked. we discussed this in slack a few days ago.

**Comment by studenton** [comment]
I added the facebook logo. Favicon size is too small.Do we have any SVG file for favicon?

![screenshot from 2016-10-30 13 06 18](https://cloud.githubusercontent.com/assets/8587189/19835038/d9599fa0-9ea1-11e6-96ff-dc1b11d31973.png)

**Comment by studenton** [comment]
@ravinepal I added facebook logo for now.

**Comment by ravinepal** [comment]
thanks, @studenton! appreciate it!
